on: [pull_request]

name: CI Pull Request

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: boa-dev/criterion-compare-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
